version: '3.8'

services:
  ultex-cloud:
    build: .
    container_name: ultex-cloud-app
    restart: unless-stopped
    ports:
      # Exposes the container's internal port 3000 to port 3050 on your Ubuntu host
      - "3050:3000"
    volumes:
      # Maps your actual Ubuntu folder to the container
      - ./:/app/shared_folder
