server {
    listen 80;
    server_name folders.ultex.ma;
    
    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name folders.ultex.ma;

    # Path to your self-signed certificates
    ssl_certificate /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    # Nginx reverse proxy to Node.js backend
    location / {
        # Assuming 172.17.0.1 is your host machine's IP inside Docker.
        proxy_pass http://172.17.0.1:3050;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Allow large file uploads
        client_max_body_size 50G; 
    }
}
